from math import sin, cos, tan, radians
angulo = float(input("Digite o ângulo: "))
angulo = radians(angulo)
seno = sin(angulo)
cosseno = cos (angulo)
tangente = tan (angulo)
print(f"O ângulo de {angulo} tem o SENO de {seno:.2f} ")
print(f"O ângulo de {angulo} tem o COSSENO de {cosseno:.2f}")
print(f"O ângulo de {angulo} tem a TANGENTE de {tangente:.2f}")
print("Python é top 🔥😎")